name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  CQube-Impl:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14, 16, 18]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
          cache-dependency-path: ./impl/c-qube/yarn.lock
      - name: build
        working-directory: impl/c-qube
        run: |
          yarn install
          yarn build

      - name: Tests
        working-directory: impl/c-qube
        run: |
          yarn test
          yarn test:cov
